project:
  type: website
  output-dir: docs

website:
  title: "Blog Posts"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/vishwasgpai/
      - icon: github
        href: https://github.com/Threepointone4
format:
  html:
    theme: cosmo
    css: styles.css



